### ISSUE TITLE
Errors when trying to run the classifier

### ISSUE THREAD

**Issue by adarshp** [tamu-nlp/Dialogue-Act-Classification#3]
@Ayesha55 - I'm getting a couple of errors.

When I tried running `python run_test.py` in the `main` branch, I got the following errors:

```
No gpu found
Traceback (most recent call last):
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/run_test.py", line 1, in <module>
    from inference import Predictor
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/inference.py", line 2, in <module>
    from baseline_model import Classifier
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/baseline_model.py", line 22, in <module>
    elmo = Elmo(options_file, weight_file, 1, dropout=0.0, requires_grad=False)
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 118, in __init__
    self._elmo_lstm = _ElmoBiLm(  # type: ignore
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 511, in __init__
    self._token_embedder = _ElmoCharacterEncoder(
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 296, in __init__
    with open(cached_path(options_file), "r") as fin:
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/common/file_utils.py", line 325, in cached_path
    raise FileNotFoundError(f"file {url_or_filename} not found")
FileNotFoundError: file ../data/elmo_2x4096_512_2048cnn_2xhighway_options.json not found
```

I then made a new branch to fix the path issues, `gitlab_deployment`, but after making those fixes, I'm getting a new error:

```
No gpu found
Traceback (most recent call last):
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/run_test.py", line 1, in <module>
    from inference import Predictor
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/inference.py", line 2, in <module>
    from baseline_model import Classifier
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/baseline_model.py", line 24, in <module>
    elmo = Elmo(options_file, weight_file, 1, dropout=0.0, requires_grad=False)
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 118, in __init__
    self._elmo_lstm = _ElmoBiLm(  # type: ignore
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 511, in __init__
    self._token_embedder = _ElmoCharacterEncoder(
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 303, in __init__
    self._load_weights()
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 387, in _load_weights
    self._load_char_embedding()
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 393, in _load_char_embedding
    with h5py.File(cached_path(self._weight_file), "r") as fin:
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/h5py/_hl/files.py", line 455, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

Do you have why this would be?

**Comment by Ayesha55** [comment]
I will look into the errors and get back to you.

**Comment by Ayesha55** [comment]
There was some issue with the uploaded elmo weights file. I have reuploaded it and it seems to be working fine on my system. Let me know if you're still facing issues.

**Comment by adarshp** [comment]
Hi @Ayesha55 - I'm getting the following error after pulling your latest changes to the `main` branch and running `python run_test.py`:

```
(tomcat) ~/git/tamu-nlp/Dialogue-Act-Classification (main) $ python run_test.py
No gpu found
Traceback (most recent call last):
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/run_test.py", line 1, in <module>
    from inference import Predictor
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/inference.py", line 2, in <module>
    from baseline_model import Classifier
  File "/Users/adarsh/git/tamu-nlp/Dialogue-Act-Classification/baseline_model.py", line 22, in <module>
    elmo = Elmo(options_file, weight_file, 1, dropout=0.0, requires_grad=False)
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 118, in __init__
    self._elmo_lstm = _ElmoBiLm(  # type: ignore
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 511, in __init__
    self._token_embedder = _ElmoCharacterEncoder(
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/modules/elmo.py", line 296, in __init__
    with open(cached_path(options_file), "r") as fin:
  File "/Users/adarsh/.venvs/tomcat/lib/python3.9/site-packages/allennlp/common/file_utils.py", line 325, in cached_path
    raise FileNotFoundError(f"file {url_or_filename} not found")
FileNotFoundError: file ../data/elmo_2x4096_512_2048cnn_2xhighway_options.json not found
```

**Comment by Ayesha55** [comment]
I have fixed the path issue.
Also, the Elmo weights file was larger than the limit set by GitHub so I had to upload it through Git LFS. You might have to navigate to the file and manually download it.

**Comment by adarshp** [comment]
Could you please post either the command line invocations for getting the file with git LFS (I haven't used it before) or the link where I can manually download it?

**Comment by Ayesha55** [comment]
The easiest way would be to download it from here https://github.com/tamu-nlp/Dialogue-Act-Classification/blob/main/data/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5

**Comment by adarshp** [comment]
That worked, thanks!
